// This file wraps the generated PIO header
// The actual rainbow_ws2811_program is defined in rainbow_test.pio.h
// which is generated by pico_generate_pio_header in CMakeLists.txt

#pragma once

#include "rainbow_test.pio.h"
